App/urls.py
from os import name
from django.urls import path
from . import views
app_name="App"

urlpatterns = [
    path("",views.index,name="index"),
    path("post/<int:id>",views.detailPost,name="detailpost"),
    path("grouplist",views.groupsList,name="grouplist"),
    path("groupbook/<int:id>",views.groupBook,name="groupbook"),
    path("logoutuser/",views.logoutuser,name="logoutuser")
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
import os
from django.utils.translation import gettext_lazy
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin,BaseUserManager
from django.utils import timezone

# Create your models here.
class CustomAccountManager(BaseUserManager):
    def create_user(self,email,password,**other_fields):
        if not email:
            raise ValueError(gettext_lazy("You must provide an email"))
        email = self.normalize_email(email)
        user = self.model(email=email,**other_fields)

        user.set_password(password)
        user.save()

        return user

    def create_superuser(self,email,password,**other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        return self.create_user(email,password,**other_fields)




def get_avataar_path(instance,avatar):
    pass
    return os.path.join("Avatar/{0}/{1}".format(instance.email,instance.avatar))

class NewUser(AbstractBaseUser,PermissionsMixin):
    username = None
    email = models.EmailField(gettext_lazy("email address"),unique=True) 
    name = models.CharField(max_length=200,blank = True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    start_date = models.DateField(default=timezone.now)
    avatar = models.CharField(max_length=1,null=True)
    color = models.CharField(max_length=15,null=True)
    

    objects = CustomAccountManager()


    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return self.name+"("+self.email +")"


    

def get_file_path(instance,doc):
    pass
    instance.documentname = instance.document.name
    return os.path.join("doc/{0}/{1}".format(instance.title,instance.document))



class Post(models.Model):
    pass
    title = models.CharField(max_length=200)
    smalldescription = models.TextField(max_length=1000,null=True)
    body = RichTextUploadingField(null=True)
    publish = models.DateTimeField(auto_now_add=True)
    document = models.FileField(upload_to=get_file_path,null=True,blank=True)
    documentname = models.CharField(max_length=100,default="downloadable file")


    def __str__(self):
        return self.title

class Group(models.Model):
    groupName = models.CharField(max_length=300)

    def __str__(self):
        return self.groupName

def get_book_path(instance,book):
    instance.bookName = instance.book.name
    return os.path.join("book/{0}/{1}".format(instance.group.groupName,instance.book))

class Book(models.Model):
    title = models.CharField(max_length=300)
    group = models.ForeignKey(Group,on_delete=models.CASCADE)
    book = models.FileField(upload_to=get_book_path)
    bookName = models.CharField(max_length=300,default="downlodablefile")
    authors = models.CharField(max_length=300,blank=True,null=True)

    def __str__(self):
        return self.bookName+" ( "+self.group.groupName+" ) "

class Comment(models.Model):
    pass
    user = models.ForeignKey(NewUser,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete = models.CASCADE)
    comment = models.CharField(max_length=1000)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.name+" ( "+self.post.title +" ) "

    class Meta:
        ordering= ["time"]
    

App/views.py
from django.shortcuts import redirect, render
from .models import *
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.hashers import make_password, check_password
import random
# Create your views here.
def index(request):
    if request.method == "POST":
        if("login" in request.POST):
            pass
            email = request.POST.get("email")
            password = request.POST.get("password")
            user = authenticate(email=email,password = password)
            if(user is not None):
                login(request,user) 
        elif("signup" in request.POST):
            pass
            email = request.POST.get("email")
            password = request.POST.get("password")
            name = request.POST.get("name")
            print(email)
            print(email[0])
            print(email[0].upper())
            try:
                colors = ['red','Green','blue','vilot','purple','brown','orange',"#dca50a",'#b10f53',"#437807"]
                i=int(random.random()*10)
                color = colors[i]
                print(color)
                user = NewUser(email = email,name=name,password = make_password(password),color = color,avatar = email[0].upper())
                user.save()
                login(request,user)
            except:
                pass            
        return redirect("App:index")
    posts = Post.objects.all().order_by("-publish")
    return render(request,"App/index.html",{"posts":posts})

def detailPost(request,id):
    if request.method == "POST":
        if("login" in request.POST):
            pass
            email = request.POST.get("email")
            password = request.POST.get("password")
            user = authenticate(email=email,password = password)
            if(user is not None):
                login(request,user) 
        elif("signup" in request.POST):
            pass
            email = request.POST.get("email")
            password = request.POST.get("password")
            name = request.POST.get("name")
            try:
                user = NewUser(email = email,name=name,password = make_password(password))
                user.save()
                login(request,user)
            except:
                pass
        elif("cmt" in request.POST):
            try:
                comment = Comment(user=request.user,post=Post.objects.get(id=id),comment=request.POST.get("comment"))          
                comment.save()
            except:
                pass

        return redirect("App:detailpost",id)
    try:
        post = Post.objects.get(id=id)
        comments = Comment.objects.filter(post=id).order_by('-time')
        return render(request,"App/detailPost.html",{"post":post,"comments":comments})
    except:
        pass
        return redirect("App:detailpost,id")
    
def groupsList(request):
    groups = Group.objects.all()
    return render(request,"App/groupList.html",{"groups":groups})

def groupBook(request,id):
    pass
    books = Book.objects.filter(group = id)
    print(books)
    return render(request,"App/groupMaterials.html",{"books":books})

def logoutuser(request):
    pass
    logout(request)
    return redirect("App:index")

App/templates/App/detailPost.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'App/css/dashboard.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'App/css/detailPost.css' %}" />
    <link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet'>
    <title>Catch UUp!</title>
</head>


<body>

    <nav class="navbar sticky-top navbar-light bg-light">
        <span class="navbar-brand mb-0 h1"><a href="{% url 'App:index' %}" style="color: white;"
                class="text-decoration-none">Apprise!</a></span>
        <span class="nav-item mr-auto">
            <a href="{% url 'App:grouplist' %}" style="color:rgb(230, 230, 230); margin-top: 5px; font-weight: bold;"
                class="text-decoration-none nav-link">Materials&Syllabus</a>
        </span>
        <span class="float-end">
            {% if request.user.is_authenticated %}
            <a style="display: inline;" href="{% url 'App:logoutuser' %}"
                class="btn1 btn-outline-dark text-decoration-none">Logout</a>
            <p class="welcomenote" style="font-size: 12px;  color:white; ">Welcome ,
                {{request.user.name}}</p>
            {% else %}
            <button id="modal-trigger" type="button" class="btn1 btn-outline-dark text-decoration-none"
                data-toggle="modal" data-target="#loginmodal" onclick="resetform()">Login</button>
            {% endif %}
        </span>



    </nav>

    <!-- Modal to login -->


    <!-- Modal -->
    <div class="modal fade" id="loginmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content float-right mr-2 ">
                <div><button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true" style="color: red; margin:5px;">&times;</span>
                    </button></div>

                <div class="modal-body">
                    <div class="form-toggle d-flex justify-content-around">
                        <button class="btn2 btn-outline-dark" style="width: 35%;" id="login-toggle"
                            onclick="toggleLogin()">Sign in</button>
                        <button class="btn2 btn-outline-dark" style="width: 35%;" id="signup-toggle"
                            onclick="toggleSignup()">sign
                            up</button>
                    </div>

                    <div id="login-form">
                        <form method="POST" id="lf">
                            {% csrf_token %}
                            <input name="login" hidden />
                            <input class="form-control mt-2 mb-2" type="email" name="email" placeholder="Enter email "
                                required />
                            <input class="form-control mb-2" type="password" name="password"
                                placeholder="Enter password" required />
                            <center>
                                <button style="width: 40%;" type="submit"
                                    class="btn3 btn-primary mb-2 login float-end">Sign
                                    in</button>
                            </center>
                            <hr />

                        </form>
                    </div>

                    <div id="signup-form" style="display: none;">
                        <form method="POST" id="sf">
                            {% csrf_token %}
                            <input name="signup" hidden />
                            <input class="form-control mt-2 mb-2" type="email" name="email"
                                placeholder="Enter your email" required />
                            <input class="form-control mb-2" type="text" name="name" placeholder="Enter Your Name"
                                required />
                            <input class="form-control mb-2" type="password" name="password"
                                placeholder="Create password" required />
                            <center>
                                <button style="width: 40%;" type="submit" class="btn3 btn-primary mb-2 signup">create
                                    account</button>
                            </center>

                            <hr />
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>


    <div class="container mt-3">
        <section> {{post.body|safe}} </section>
        {% if post.document %}
        <div class="downlodable-file">
            <a href="{{post.document.url}}" class="text-decoration-none btn-outline-dark btn">{{post.documentname}} <svg
                    class="ml-1" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-download" viewBox="0 0 16 16">
                    <path
                        d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
                    <path
                        d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
                </svg></a>
        </div>
        {% endif %}
    </div>
    <hr>
    <div class="container">
        <h6>Make you comment here</h6>
        <div>


            <form method="POST">
                {% csrf_token %}
                <input name="cmt" hidden>
                <textarea class="form-control mb-2" style="width: 100%;" name="comment" rows="5"
                    placeholder="write your comment here" required></textarea>
                <div class="d-flex justify-content-end">
                    {% if request.user.is_authenticated %}
                    <button class="btn4 btn-primary" style="display: block;" type="submit">Submit</button>
                    {% else %}
                    <button type="button" class="btn4 btn-primary"
                        onclick="document.getElementById('modal-trigger').click() ">Submit</button>
                    {% endif %}
                </div>
            </form>
        </div>

    </div>
    <hr>
    <div class="container mt-2">
        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-12"></div>
            <div class="col-lg-8 col-sm-8 col-sm-12">
                {% for comment in comments %}
                <div class="card mb-2">
                    <div class="card-header">
                        <div class="float-left d-flex flex-row align-items-center">
                            <div class="d-flex  align-items-center mr-2 "
                                style="background:{{comment.user.color}}; border-radius:50%; color:white;  width:30px; height:30px;  text-align:center; justify-content:center; ">
                                <span>{{comment.user.avatar}}</span>
                            </div>
                            <div class="d-flex flex-column">
                                <p style="font-size: 12px;" class="m-0">{{comment.user.name}}</p>
                                <p style="font-size: 12px;" class="m-0">{{comment.time|date}}</p>
                            </div>

                        </div>



                    </div>
                    <div class="card-body" style="font-size: 12px;">
                        <p>{{comment.comment}}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src=" https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
    <script>
        function toggleSignup() {
            document.getElementById("login-form").style.display = "none";
            document.getElementById("signup-form").style.display = "block";
        }

        function toggleLogin() {
            document.getElementById("signup-form").style.display = "none";
            document.getElementById("login-form").style.display = "block";
        }

        function resetform() {
            document.getElementById('lf').reset();
            document.getElementById('sf').reset();
        }



    </script>

</body>

</html>

App/templates/App/groupList.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'App/css/dashboard.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'App/css/groupList.css' %}" />
    <link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet'>
    <title>Catch Up!</title>
</head>

<body>

    <nav class="navbar sticky-top navbar-light bg-light">
        <span class="navbar-brand mb-0 h1"><a href="{% url 'App:index' %}" style="color: white;"
                class="text-decoration-none">Apprise!</a></span>
        <span class="nav-item mr-auto">
            <a href="#" style="color:rgb(230, 230, 230); margin-top: 5px; font-weight: bold;" class="
                text-decoration-none nav-link">Materials&Syllabus</a>
        </span>

    </nav>


    <div class="container actualcontainer mt-3">
        <div class="row">
            {% for group in groups %}
            <div class="col-lg-4 col-md-4 col-sm-12">
                <div class="card mb-2 ">
                    <div class="card-body d-flex justify-content-center">
                        <a href="{% url 'App:groupbook' group.id %}"
                            class="text-decoration-none">{{group.groupName}}</a>
                    </div>
                </div>
            </div>


            {% endfor %}
        </div>


    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
</body>

</html>

App/templates/App/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'App/css/dashboard.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'App/css/index.css' %}" />
    <link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet'>
    <title>Catch Up!</title>
</head>

<body>

    <nav class="navbar sticky-top navbar-light bg-light">
        <span class="navbar-brand mb-0 h1" style="color:white;">Apprise!</span>
        <span class="nav-item mr-auto">
            <a href="{% url 'App:grouplist' %}" style="color:rgb(230, 230, 230); margin-top: 5px; font-weight: bold;"
                class="text-decoration-none nav-link">Materials&Syllabus</a>
        </span>
        <span class="float-end">
            {% if request.user.is_authenticated %}
            <a style="display: inline;" href="{% url 'App:logoutuser' %}"
                class="btn1 btn-outline-dark text-decoration-none">Logout</a>
            <p class="welcomenote" style="font-size: 12px;  color: white;">Welcome ,
                {{request.user.name}}</p>

            {% else %}
            <button type="button" class="btn1 btn-outline-dark text-decoration-none" data-toggle="modal"
                data-target="#loginmodal" onclick="resetform()">Login</button>
            {% endif %}
        </span>



    </nav>

    <!-- Modal to login -->


    <!-- Modal -->
    <div class="modal fade" id="loginmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content float-right mr-2 ">
                <div><button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true" style="margin:5px; color: red;">&times;</span>
                    </button></div>

                <div class="modal-body">
                    <div class="form-toggle d-flex justify-content-around">
                        <button class="btn2 btn-outline-dark" style="width: 35%;" id="login-toggle"
                            onclick="toggleLogin()">Sign in</button>
                        <button class="btn2 btn-outline-dark" style="width: 35%;" id="signup-toggle"
                            onclick="toggleSignup()">sign
                            up</button>
                    </div>

                    <div id="login-form">
                        <form method="POST" id="lf">
                            {% csrf_token %}
                            <input name="login" hidden />
                            <input class="form-control mt-2 mb-2" type="email" name="email" placeholder="Enter email "
                                required />
                            <input class="form-control mb-2" type="password" name="password"
                                placeholder="Enter password" required />
                            <center><button style="width: 40%;" type="submit"
                                    class="btn3 btn-primary mb-2 login float-end">Sign
                                    in</button></center>
                            <hr />

                        </form>
                    </div>

                    <div id="signup-form" style="display: none;">
                        <form method="POST" id="sf">
                            {% csrf_token %}
                            <input name="signup" hidden />
                            <input class="form-control mt-2 mb-2" type="email" name="email"
                                placeholder="Enter your email" required />
                            <input class="form-control mb-2" type="text" name="name" placeholder="Enter Your Name"
                                required />
                            <input class="form-control mb-2" type="password" name="password"
                                placeholder="Create password" required />
                            <center>
                                <button style="width: 40%;" type="submit" class="btn3 btn-primary mb-2 signup">create
                                    account</button>
                            </center>

                            <hr />
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>


    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-12"></div>
            <div class="col-lg-8 col-md-8 col-sm-12">
                {% for post in posts %}
                <div class="card mb-2">
                    <div class="card-header ">
                        <center>
                            <b class="post-title card-title">{{post.title}}</b>
                        </center>
                    </div>
                    <div class="card-body">
                        <p class="card-text post-description">{{post.smalldescription}}</p>

                        <a href="{% url 'App:detailpost' post.id %}" class="float-end text-decoration-none">Continue
                            Reading<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-arrow-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z" />
                            </svg></a>


                    </div>
                </div>

                {% endfor %}
            </div>

            <div class="col-lg-2 col-md-2 col-sm-12"></div>
        </div>

    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->

    <script>
        function toggleSignup() {
            document.getElementById("login-form").style.display = "none";
            document.getElementById("signup-form").style.display = "block";
        }

        function toggleLogin() {
            document.getElementById("signup-form").style.display = "none";
            document.getElementById("login-form").style.display = "block";
        }

        function resetform() {
            document.getElementById('lf').reset();
            document.getElementById('sf').reset();
        }

    </script>

</body>

</html>